import base64
import json

import solders
import solders.message
from solana.rpc.api import Client
from solana.rpc.commitment import Processed
from solana.rpc.types import TxOpts
from solders.keypair import Keypair
from solders.transaction import VersionedTransaction

from app.config import settings

# Constants
# WALLET_ADDRESS = "YOUR_WALLET_ADDRESS_PUBLIC_KEY"
# INPUT_MINT = "So11111111111111111111111111111111111111112"
# OUTPUT_MINT = "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"
# AMOUNT = 5000000
# QUOTE_URL = f"https://quote-api.jup.ag/v6/quote?inputMint={INPUT_MINT}&outputMint={OUTPUT_MINT}&amount={AMOUNT}"
# SWAP_URL = "https://quote-api.jup.ag/v6/swap"
PRIVATE_KEY = Keypair.from_bytes(bytes.fromhex(settings.SOL_PRIVATE_KEY_HEX))

# # Get quote response
# quote_response = requests.get(url=QUOTE_URL).json()

# # Prepare swap payload
# payload = {
#     "quoteResponse": quote_response,
#     "userPublicKey": WALLET_ADDRESS,
#     "wrapUnwrapSOL": True
# }

# Initialize Solana client
client = Client(endpoint=settings.SOLANA_MAINNET_ENDPOINT)
swapTransaction = "AgAAAAAAAABXAAAAAAAAAFlVWHAzWGM1Zk1VRFRnSmN4cXFoUEZ4S21YYnFDU1FoOGdFNTlRbUR2TkMyVW5ERGVyV1JCN0Y0RHF3TGdBV3FmMVNoQ3ZkNENycW5Vd0ZweVJuM0p2OVgAAAAAAAAANFpTa2lHZ3RROUpzM2FYNWs2WWZWeVFVTkszTXJTaDdENHEycHZ4RGl6TVRoSkY0Nlp3eDczcFI5UnVkWEs4aUJWNEhvOHdGM05GQ0NmaFJwSm15cVp3QwIBBhQAAAAAAAAALAAAAAAAAAA0cXpLUG1QUm9Fd250QWtra0x5cUppaVI5Uk5aMnBLcDRQQkEzM2pBU1RUTSsAAAAAAAAATlRZZVlKMXdyNGJwTTV4bzZ6eDVFbjQ0U3ZKRkFkMzV6VHh4Tm9FUllxZCwAAAAAAAAANWREV2lkWjdkSEwzWmZpSG1DZWlTRnF1dkw5SExxdVVncWQ3TTZCZDZZeHYsAAAAAAAAADNkZ0NDYjE1SE1RU0E0UG4zVGZpaTV2Ums3YVJxVEg5NUxKanh6c0cyTXVnLAAAAAAAAABBQzYxUVdkOUZkSFFOSFRWQ1FFb0pOQmV2OUttTFppMXNxNVRQSDJNOXV1ZSwAAAAAAAAAOGF2TnZnQWRua0FYR1A5bm8xcmZzS1F6UlRVTmZnUEVSd1VEQ0ZmSFE1cnEsAAAAAAAAAEVYUFBQbzQ4R05WQ0RDV2dydlpiWlhQaThoZGI4TU1IaFZ1Uzc0WWJqRGs0LAAAAAAAAABFUkw5V2tTVnlOZ3NadGpDa2c0Z3NqUkhYaEZmamlONk5mSmd4UG5Mb3B3WCwAAAAAAAAAQ3BZTkZLbkd0azl5S3c4UFNRVHpSVEd0OEI3YnhUTTJScDR3OFc0WktmWDEsAAAAAAAAAENXRGM1Y0hHQmRwbkFqdUJlMWc5R3R1bkdjZnY0Y2hKRkxqdXNVdGZncjFHLAAAAAAAAABKQnBCY0IyZlp3Rkhvc3l0YW93bzFXM2VyUWF0TVd5UmtNdGc4YjY4TWdIUCwAAAAAAAAARXE1OWNDRUdRQzNnQnc3Z0J4WGpZdEZ4bW8yS1RUVEF5cmtKZDRydEtobXUrAAAAAAAAAGo2RFNyYzlMYmUzOEtZVlhMdlBYUzlUVUtyaVFEVGVnUkhLUkI4eVpRVlgsAAAAAAAAAERaRmRLeWgxNmIzVGdvR2V4VXpFZ3BOeFZnQ3Jka3V4RXNYM2FXc1RaWGtxKwAAAAAAAABDb21wdXRlQnVkZ2V0MTExMTExMTExMTExMTExMTExMTExMTExMTExMTExKwAAAAAAAABNMm14OTNla3QxZm1YU1ZrVHJVTDl4VkZIa21NRThIVFVpNUN5YzVhRjdLLAAAAAAAAABHdXdXaVNBNzVWdVFIM2VOUWpUUWk5blBxbmRUZVU4QnhiQlVpWTFBY0xQNSwAAAAAAAAAQ29SRUVOeFQ2dFcxSG9LOHlwWTFTeFJNWlRjVlBtN1I5NHJINFBaTmhYN2QsAAAAAAAAAEo5UkNRWVB4bWNTQzFMZHlBVHozTmlndERLSnducFIxWk51RmNSVWI1YTdILAAAAAAAAAA2ZTRTdXd4NXZWcmJ0Y1lITUYyOGNpQ1B6cVNNTG9yRUVkdXR6V0o3RTJHZSwAAAAAAAAANWRXVGlIRW1OcVlON2VFM1JyUTNBM1NCM1VBUG1jYTRBbllBOVJURjUzM1IFAAAAAAAAAA4AAAAAAAAAAAYAAAAAAAAAS0VVTXVaAA4AAAAAAAAAAAwAAAAAAAAAM3FqOUZYWlI5VDVxAA8LAAAAAAAAAAABAhUWFwMEBRgZGAAAAAAAAAAzR3lXcmtzc1cxMndTZzV2UG1DMzl1MncADw0AAAAAAAAAAAEGEAIVFgcVERcDBTQAAAAAAAAAVUVWWUpyem1ldjJVR1lFc3NUYk1tU1lNcUhyM1cxbm1BQnM5WE1FWFoyZzRMYlJaNkNwNwAPGAAAAAAAAAAAAAgBGgYWFAkHAhUSERcTAwUKCxgMDRkdAAAAAAAAAEU4M1VpRkh6SnZDNldrR3BZdHFaYkJCcWdDRnNEAAEBAAAAAAAAACwAAAAAAAAAOUpxRXd2Z2lTTGQ1Z3ZNS3RLWFRZdG1LQnVoQnlHUlplN2lQekhOUWQ0czMBAAAAAAAAAC4GAAAAAAAAAAsJAAECDQ=="
# Decode and sign the transaction
raw_transaction = VersionedTransaction.from_bytes(base64.b64decode(swapTransaction))
signature = PRIVATE_KEY.sign_message(
    solders.message.to_bytes_versioned(raw_transaction.message)
)
signed_txn = VersionedTransaction.populate(raw_transaction.message, [signature])

# Send the signed transaction
opts = TxOpts(skip_preflight=False, preflight_commitment=Processed)
# simulation_result = client.send_raw_transaction(signed_txn)
result = client.send_raw_transaction(txn=bytes(signed_txn), opts=opts)

# Extract and print the transaction ID
transaction_id = json.loads(result.to_json())["result"]
print(f"Transaction sent: https://explorer.solana.com/tx/{transaction_id}")
